import { Inter } from "next/font/google";
import { AuthProvider } from "@/context/userContext";
import MyApp from "./_app.jsx";
import ThemeRegistry from "../../theme/ThemeRegistry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ThemeRegistry>
            <MyApp>{children}</MyApp>{" "}
          </ThemeRegistry>
        </AuthProvider>
      </body>
    </html>
  );
}
